name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker build . --file Dockerfile --tag ghcr.io/$REPO_LOWER:${{ github.run_id }}
        docker push ghcr.io/$REPO_LOWER:dev-build-${{ github.run_number }}