name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest #Currently using hosted but will switch to self-hosted runner when repo is private
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        docker build . --file Dockerfile -t ghcr.io/$REPO_LOWER/dev-build:${{ github.run_number }}
        docker push ghcr.io/$REPO_LOWER/dev-build:${{ github.run_number }}